version: '3.8'

services:
  leetcode-bot:
    build: .
    container_name: leetcode-telegram-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_GROUP_ID=${TELEGRAM_GROUP_ID}
      - DATABASE_PATH=/data/leetcode_bot.db
      - PROBLEMS_FILE_PATH=./problem_deduplicated.yaml
      - TIMEZONE=Asia/Ho_Chi_Minh
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "test", "-f", "/data/leetcode_bot.db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  data: 